server/.gitignore, server/nodemon.json, server/package.json, server/src/index.ts, server/tsconfig.json
Close #1 
1. tsconfig 설정
2. nodemon 설정
3. koa hello world!
=> chore : server init

.gitignore, client/.storybook/main.js, client/.storybook/preview.js, client/package.json, package.json, server/.gitignore
Close #9 #11
- 스토리북 설정 추가
- yarn workspace 설정 추가
=> 스토리북 설정 & yarn workspace 설정 추가

client/package.json, package.json, server/package.json, yarn.lock
Close #3 
pre-commit 단계에서 코드 포맷 검사/수정을 진행하는 hook을 설정했습니다.
husky가 소스트리같은 GUI를 이용할 때 동작하지 않는 문제가 있어서 다른 방법을 적용해보려고 했는데 찾아보니 mac 환경에서만 발생하는 문제인 것 같아서 그대로 진행했는데 해당 pr이 merge된 이후에 소스트리를 이용하셨을 때 pre-commit 훅이 동작하는지 확인 부탁드립니다. (@sangw3433)
=> Precommit hook 설정

.github/auto_assign.yml
- 팀명으로 등록했을 때 동작하지 않는 이슈가 있어서 개별 등록으로 수정함.
=> fix: auto_assign.yml 리뷰어 목록 수정

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/issue------.md, .github/PULL_REQUEST_TEMPLATE.md
- mention 이 제대로 이루어지지 않아서 
- @boostcamp-2020 추가 
- pull request, issue에서 멘토분들 자동으로 멘션할 수 있다. 
@AccountBook_Mentor
=> chore : template mention 수정

server/package.json, server/src/auth/auth.router.ts, server/src/loader/index.ts, server/src/loader/router.ts
Close #18 
- auth 폴더 구조 및 router 추가 
- loader 에 router 추가 
=> auth 폴더구조 추가

server/package.json, server/src/auth/auth.service.ts, server/src/auth/types/decodedJWT.ts, server/src/auth/types/userDTO.ts
Close #
- JWT 토큰 발급 기능 유효기간 24시간으로 설정
- JWT 토큰을 이용한 인증기능 구현
- 토큰 인증 시 유효기간 4시간 미만일 경우 새로운 토큰 발급
=> JWT 토큰 발급, 인증기능 구현

server/src/auth/auth.router.ts, server/src/auth/auth.service.ts, server/src/auth/types/kakao-user-dto.ts, server/src/auth/types/kakao-user-info.ts, server/src/auth/types/naver-user-dto.ts, server/src/auth/types/social-user-dto.ts, server/src/user/user.service.ts
Close #17
- kakao user dto types 수정 
- naver OAuth 구현 
- 네이버 아이디로 로그인할 수 있다. 
=> naver OAuth 구현

server/src/config/orm/snake-naming-strategy.ts, server/src/seed/seed-generator.ts, server/src/seed/test.seed.ts, server/src/seed/up.ts
Close #56, #58 
- DB 테이블명 네이밍 전략 수정
- 테이블의 이름이 snake_case로 매핑되지 않는 문제를 확인하고 수정했습니다.
- **확인할 사항** ✅
- 변경된 테이블명으로 sync가 진행되면 기존의 Payment 테이블과 새로 생성된 payment 테이블처럼 case만 다른 경우는 서로 같은 테이블로 인식되어 오류가 발생합니다. 
- 로컬이나 별도로 사용하던 DB의 테이블을 모두 삭제한 다음 새로 sync를 해주세요.
- 테이블을 삭제한 다음 sync를 진행했는데도 오류가 발생한다면 database(accountbook)를 삭제한 다음 다시 생성하고 sync를 진행해주세요.
- Seeder 모듈 리팩토링
- seed 모듈을 목적에 따라 유연하게 사용할 수 있도록 데이터 생성에 필요한 인자를 입력받도록 변경했습니다.
- 테스트용 Seeder 모듈을 구현했습니다.
=> DB 테이블 네이밍 전략 수정, Seeder 모듈 리팩토링

client/src/components/common/buttons/modalToggleButton/index.tsx, client/src/components/common/buttons/modalToggleButton/style.tsx, client/src/components/common/buttons/modalToggleButton/types.tsx
Close #67
- button 을 통해 모달을 열 수 있다! 
=> modal Toggle Button 구현 

client/src/libs/axios.ts, client/src/libs/endpoints.ts
Close #82 
- 백엔드 API 호출/응답을 일관성 있게 처리하기 위해 baseURL, response interceptor를 설정한 Axios 인스턴스를 생성했습니다.
- API 호출에 사용되는 endpoint를 상수화 시켰습니다.
```javascript
import axios from '@/libs/axios';
import endpoints from '@/libs/endpoints';
const transactions = await axios.get(`${endpoints.TRANSACTION_API}?year=2020&month=11`);
```
=> Axios 설정 모듈화

client/src/commons/types/transaction.ts, client/src/components/common/Modal/index.tsx, client/src/components/common/Modal/types.ts, client/src/components/transaction/ModalRadioButton/index.tsx, client/src/components/transaction/ModalRadioButton/types.ts, client/src/container/TransactionModal/index.tsx, client/src/libs/api/transaction.ts, client/src/modules/index.ts, client/src/modules/transaction/actions.ts, client/src/modules/transaction/index.ts, client/src/modules/transaction/reducer.ts, client/src/modules/transaction/thunks.ts, client/src/modules/transaction/types.ts
- 수입/ 지출에 따른 카테고리 변경 
- transaction module 추가 
=> modal radio button 작동 및 transaction module 추가 

client/public/index.html, client/src/App.tsx, client/src/commons/types/category.ts, client/src/commons/types/payment.ts, client/src/components/common/forms/CustomInput/index.tsx, client/src/components/common/forms/CustomInput/types.ts, client/src/components/common/forms/CustomSelectInput/index.tsx, client/src/components/common/forms/CustomSelectInput/types.ts, client/src/components/transaction/ModalRadioButton/index.tsx, client/src/components/transaction/ModalRadioButton/types.ts, client/src/container/TransactionModal/index.tsx, client/src/libs/createAsyncThunk.ts, client/src/modules/index.ts, client/src/modules/transaction/actions.ts, client/src/modules/transaction/aggregateUtil.ts, client/src/modules/transaction/reducer.ts, client/src/modules/transaction/types.ts, client/src/views/Calendar/index.tsx, client/src/views/DashBoardPage/index.tsx, client/tsconfig.json, server/src/domain/transaction/transaction.service.test.ts, server/src/domain/transaction/transaction.service.ts, server/src/domain/transaction/types.ts
- transaction reducer 및 상태 변경 
=> Post 기능 상태관리 변경사항들 추가 

client/public/index.html, client/src/App.tsx, client/src/commons/dto/category.ts, client/src/commons/dto/payment.ts, client/src/commons/dto/transaction-request.ts, client/src/commons/types/category.ts, client/src/commons/types/payment.ts, client/src/commons/types/transaction.ts, client/src/components/common/forms/CustomInput/index.tsx, client/src/components/common/forms/CustomInput/types.ts, client/src/components/common/forms/CustomSelectInput/index.tsx, client/src/components/common/forms/CustomSelectInput/types.ts, client/src/components/transaction/ModalRadioButton/index.tsx, client/src/components/transaction/ModalRadioButton/types.ts, client/src/container/TransactionModal/index.tsx, client/src/libs/api/transaction.ts, client/src/libs/createAsyncThunk.ts, client/src/modules/index.ts, client/src/modules/transaction/actions.ts, client/src/modules/transaction/aggregateUtil.ts, client/src/modules/transaction/reducer.ts, client/src/modules/transaction/types.ts, client/src/views/Calendar/index.tsx, client/src/views/DashBoardPage/index.tsx, client/tsconfig.json, server/src/domain/transaction/transaction.service.test.ts, server/src/domain/transaction/transaction.service.ts, server/src/domain/transaction/types.ts
Close #107 
- transaction 상태관리 논의사항 반영
- 모달 transaction post 동작 수정( DTO 를 통해 올바른 타입 전송) 
- post 이 후의 모달 닫기 추가 
=> transaction 상태관리 수정 및 모달 동작 수정 

client/src/GlobalStyled.ts, client/src/components/common/layouts/Header/styles.ts, client/src/components/common/layouts/MainLayout/styles.ts, client/src/components/transaction/ListItem/index.stories.tsx, client/src/components/transaction/ListItem/index.tsx, client/src/components/transaction/ListItem/styles.ts, client/src/components/transaction/ListItem/types.ts, client/src/container/DashboardDetails/index.tsx, client/src/container/DashboardDetails/styles.ts, client/src/container/DashboardMain/index.tsx, client/src/libs/api/transaction.ts, client/src/modules/transaction/actions.ts, client/src/modules/transaction/reducer.ts, client/src/modules/transaction/thunks.ts, client/src/modules/transaction/types.ts, client/src/views/DashBoardPage/index.tsx, server/src/domain/transaction/transaction.service.test.ts, yarn.lock
Close #
- TransactionState 타입을 정의할때 오타가 있었던 부분을 수정했습니다.
- TransactionListItem 컴포넌트를 필요에 따라 border를 추가할 수 있도록 border prop을 추가했습니다.
- TransactionListItem 컴포넌트에서 overflow:hidden 속성에 의해 잘리는 것을 방지하기 위해 line-height값을 1rem -> 1.1rem 으로 수정했습니다.
- 대시보드 내역 컨테이너 구현
- 고정 지출 내역 부분과 통계 탭은 작업이 합쳐져야 해서 비워두었습니다.
=> Dashboard 내역 컨테이너 구현

client/src/components/common/Dropdown/styles.ts, client/src/components/common/SelectMonth/index.stories.tsx, client/src/components/common/SelectMonth/index.tsx, client/src/components/common/SelectMonth/styles.tsx, client/src/components/common/SelectMonth/type.ts, client/src/modules/index.ts
Close #92 
- 기능 목록
월 표시, 버튼 클릭 시 드랍다운
-추후 개발 목록
리덕스 도입 시 버튼과 달력 동기화
=> 월 선택 컴포넌트 구현

client/src/components/calendar/CalendarView/index.tsx, client/src/components/calendar/TableCell/index.tsx, client/src/components/common/Dropdown/index.tsx, client/src/components/common/Dropdown/styles.ts, client/src/container/Calendar/index.tsx
Reverts boostcamp-2020/Project16-F-Account-Book#123
=> Revert "드랍다운 이외의 공간 클릭 시 드랍다운 컴포넌트 제거 구현"

client/src/components/common/Dropdown/index.tsx, client/src/components/common/Dropdown/styles.ts
Close #
드랍다운 버튼 이외 클릭 이벤트 스타일 추가
=> [Feature]드랍다운 버튼 이외 클릭 이벤트 스타일 추가

client/src/GlobalStyled.ts, client/src/components/common/Dropdown/index.tsx, client/src/components/common/Dropdown/styles.ts, client/src/container/Calendar/index.tsx, client/src/container/DashboardDetails/index.tsx, client/src/container/SelectMonth/index.tsx, client/src/libs/api/transaction.ts, client/src/libs/dateUtils.ts, client/src/modules/transaction/reducer.test.ts, yarn.lock
Close #137
- DateUtil에서 날짜정보를 parsing 했을때 반환 값 변경
- month값에 +1 을 해서 반환
=> DateUtil 리팩토링 진행

client/src/components/manage/ManageItem/index.tsx, client/src/components/manage/ManageItem/types.tsx, client/src/components/manage/ManageItemInput/index.tsx, client/src/components/manage/ManageItemInput/types.tsx, client/src/container/PaymentManageMain/index.tsx, client/src/modules/payment/actions.ts, client/src/modules/payment/reducer.ts, client/src/modules/payment/thunks.ts, server/src/domain/payment/payment.router.ts, server/src/domain/payment/payment.service.ts, server/src/entity/payment.entity.ts
Close #135 
- 결제수단 추가, 수정, 삭제 기능 구현 (module, manageContainer)
- 결제수단 관련 api 수정(create, update, delete 시에도 paymentEntity 반환하도록 설정)
=> 결제수단 관리 페이지 기능 구현 

client/src/commons/dto/category-request.ts, client/src/commons/types/category.ts, client/src/components/manage/ManageItem/index.tsx, client/src/components/manage/ManageItem/types.tsx, client/src/components/manage/ManageItemInput/index.tsx, client/src/components/manage/ManageItemInput/types.tsx, client/src/container/CategoryManageMain/index.tsx, client/src/container/CategoryManageMain/styles.tsx, client/src/container/CategoryManageMain/types.tsx, client/src/container/PaymentManageMain/index.tsx, client/src/container/TransactionModal/index.tsx, client/src/libs/api/category.ts, client/src/modules/category/actions.ts, client/src/modules/category/reducer.ts, client/src/modules/category/thunks.ts, client/src/modules/category/types.ts, client/src/modules/payment/actions.ts, client/src/modules/payment/reducer.ts, client/src/modules/payment/thunks.ts, server/src/domain/category/category.router.ts, server/src/domain/category/category.service.ts, server/src/domain/payment/payment.router.ts, server/src/domain/payment/payment.service.ts, server/src/entity/category.entity.ts, server/src/entity/payment.entity.ts
Close #144
- 카테고리 추가, 수정, 삭제 기능 구현 (module, manageContainer)
- 카테고리관련 api 수정(create, update, delete 시에도 categoryEntity 반환하도록 설정)
=> 카테고리 관리 container 구현 

package.json
Close #149 
- 이미지를 실행할때 업데이트 된 이미지로 pull 받는 요청을 추가했습니다.
- 서버/프론트 이미지를 개별적으로 실행할 수 있도록 명령어를 추가하고 실행 명령어를 수정했습니다.
**전체실행** : `npm run docker` (또는 `yarn docker`)
**실행종료** : `npm run docker:down` (또는 `yarn docker:down`)
**서버만 실행** : `npm run docker:server` (또는 `yarn docker:server`)
**클라이언트만 실행** : `npm run docker:client` (또는 `yarn docker:client`)
=> fix: pre-release 버전 이미지 실행 스크립트 수정

client/src/container/Calendar/index.tsx, client/src/container/Calendar/styles.ts, client/src/container/SelectMonth/index.tsx, client/src/container/SelectMonth/styles.tsx
드랍다운 형식이 아닌 클릭으로 인한 date변경으로 수정
=> date 선택 방법 변경

client/src/components/common/layouts/Header/index.tsx, client/src/components/transaction/ListItem/index.tsx, client/src/components/transaction/ListItem/styles.ts, client/src/components/transaction/ListItem/types.ts, client/src/container/DashboardContainer/index.tsx, yarn.lock
- merge 후 작업이 합쳐지면서 오류가 발생하는 부분을 수정했습니다.
=> fix: merge 후 오류 발생부분 수정

client/src/components/transaction/EmptyState/index.tsx, client/src/components/transaction/EmptyState/styles.ts, client/src/components/transaction/EmptyState/types.ts, client/src/container/DashboardContainer/index.tsx, client/src/container/TransactionList/index.tsx, client/src/container/TransactionSelectList/index.tsx
- 거래내역이 공백시 거래내역이 없음을 표시할 수 있다. 
=> fix : 공백상태 관리를 위한 EmptyState 컴포넌트 구현 

client/src/container/DashboardContainer/styles.ts, client/src/container/SelectMonth/index.tsx, client/src/container/SelectMonth/styles.tsx
- 대시보드에서 레이아웃에 맞춘 설정이 달력 페이지에도 영향을 주던 문제를 수정했습니다.
=> fix: 월 선택 컴포넌트 위치 수정

client/src/components/fixedExpenditure/Item/index.tsx, client/src/container/FixedExpenditure/index.tsx, server/src/domain/fixed-expenditure/fixed-expenditure.service.ts
Close #176 
- 고정 지출 API 쿼리 수정
- 거래 내역 추가시 고정 지출 업데이트
- 고정 지출 날짜 하루 전으로 나오는 부분 수정
=> 고정 지출 버그 수정

client/src/container/CategoryManageContainer/index.tsx, client/src/container/CategoryManageMain/index.tsx
Close #180 
- 수입 카테고리에서 추가시 지출 카테고리로 생성되는 버그 수정
- input 창이 재 랜더링 되지 않아 isIncome 속성이 변하지 않았던 문제를 key값을 추가하여 동일한 컴포넌트로 인식하지 않도록 하여 해결 
=> fix : 카테고리 관리페이지 버그 수정

client/src/App.tsx, client/src/components/transaction/LineGraph/index.tsx, client/src/components/transaction/LineGraph/styles.tsx, client/src/components/transaction/LineGraph/types.ts, client/src/container/DashboardContainer/index.tsx, client/src/container/LineGraphContainer/index.tsx, client/src/container/LineGraphContainer/style.tsx, client/src/container/LineGraphContainer/styles.ts, client/src/container/LineGraphContainer/types.tsx, client/src/views/AggregateCategoryPage/index.tsx, client/src/views/AggregatePeriodPage/index.tsx
=> 꺽은선 그래프 통계페이지 구현 

client/src/components/common/buttons/CustomButton/index.tsx, client/src/components/common/buttons/CustomButton/types.tsx, client/src/components/manage/ManageItemInput/index.tsx, client/src/components/manage/ManageItemInput/types.tsx, client/src/container/CategoryManageContainer/index.tsx, client/src/container/PaymentManageMain/index.tsx, client/src/libs/checkOverlap.ts, client/src/libs/checkValidation.ts
Close #196
- 데이터 중복시 저장 disabled
- blank 허용 
- 앞,뒤 blank 미허용
- 커스텀 버튼 기능 추가
isValid로 버튼 disabled 조정 가능 
- isValid === true   버튼 사용가능
- isValid === false 버튼 사용 불가능
=> 카테고리/결제수단 유효성 검사 추가

client/src/GlobalStyled.ts, client/src/components/common/buttons/CustomButton/index.tsx, client/src/components/common/buttons/CustomButton/types.tsx, client/src/components/common/forms/CustomSelectInput/index.tsx, client/src/components/manage/ManageItemInput/index.tsx, client/src/components/manage/ManageItemInput/types.tsx, client/src/container/CategoryManageContainer/index.tsx, client/src/container/PaymentManageMain/index.tsx, client/src/container/TransactionModal/index.tsx, client/src/container/TransactionUpdateModal/index.tsx, client/src/libs/checkOverlap.ts, client/src/libs/checkValidation.ts
Close #111
- 기능 목록
**거래내역 추가** 
모든 항목이 선택되지 않으면, amount나  상세내용 비어 있을 시버튼 disabled
**거래내역 수정**
모든 항목이 선택되지 않으면, amount나  상세내용 비어 있을 시버튼 disabled
=> 거래내역 등록, 수정 시 유효성 검사

client/src/container/TransactionModal/index.tsx
- 웹 상에서 충돌을 해결하면서 eslint 오류 부분을 수정
=> eslint 오류 수정 

server/src/domain/fixed-expenditure/fixed-expenditure.service.ts, server/src/entity/fixed-expenditure.entity.ts, server/src/entity/transaction.entity.ts
잘못 사용된 인라인 뷰 제거 후 left outer join에 맞는 쿼리로 변경
Close #185
- 고정 지출 쿼리 변경
- DB 인덱스 설정하여 고정 지출 쿼리 실행 시간 단축
=> 고정 지출 쿼리 수정

client/src/App.tsx, client/src/components/common/LoadingSpinner/styles.ts, client/src/container/DashboardContainer/index.tsx, client/src/container/FixedExpenditure/index.tsx
- react lazy 적용 ( code spliting )
-> dynamic import 를 사용하여 app 성능 개선 
- lazy 적용 전 
- lazy 적용 후
약간의 app 성능 상승이 있음을 확인하였습니다. 
- dashboard 페이지 거래내역 불러올시 로딩컴포넌트 제거
-> 화면이 깜빡거리는 현상이 ux에 부정적인 영향을 줄 거라 판단하여 제거 
- https://reactjs.org/docs/code-splitting.html#reactlazy
=> react lazy 적용 
